// Generated by CoffeeScript 1.8.0
window.addEventListener("load", function() {
  var app, autoCompleteWin, html, input, myDirective, viewport;
  app = angular.module("Binged", []);
  html = document.querySelector("html");
  html.setAttribute("ng-app", "");
  html.setAttribute("ng-csp", "");
  viewport = document.getElementById("viewport");
  viewport.setAttribute("ng-controller", "MainController");
  app.controller("MainController", function($scope) {});
  autoCompleteWin = document.querySelector(".sbdd_b");
  angular.element(autoCompleteWin).remove();
  input = document.getElementById("lst-ib");
  input.setAttribute("ng-model", "search");
  myDirective = document.createElement("div");
  myDirective.setAttribute("my-directive", "");
  document.querySelector(".jsb center").appendChild(myDirective);
  app.directive("myDirective", [
    '$sce', function($sce) {
      return {
        restrict: 'EA',
        replace: true,
        templateUrl: $sce.trustAsResourceUrl(chrome.extension.getURL("templates/bing.html"))
      };
    }
  ]);
  return angular.bootstrap(html, ['Binged'], []);
});
