// Generated by CoffeeScript 1.8.0
(function() {
  window.addEventListener("load", function() {
    var app, html, myDirective, project_tabs, template1, viewport;
    app = angular.module("Binged", []);
    html = document.querySelector("html");
    html.setAttribute("ng-app", "");
    html.setAttribute("ng-csp", "");
    viewport = document.getElementById(":26");
    viewport.setAttribute("ng-controller", "MainController");
    app.controller("MainController", function($scope) {});
    myDirective = document.createElement("div");
    myDirective.setAttribute("my-directive", "");
    viewport.appendChild(myDirective);
    project_tabs = '<div class="Wn" id=":26"> <button class="gbqfba" aria-label="Google Search" id="gbqfba" name="btnK"><span id="gbqfsa">EMAIL</span></button> <button class="gbqfba" aria-label="Google Search" id="gbqfba" name="btnK"><span id="gbqfsa">TASKS</span></button> <button class="gbqfba" aria-label="Google Search" id="gbqfba" name="btnK"><span id="gbqfsa">FILES</span></button> <button class="gbqfba" aria-label="Google Search" id="gbqfba" name="btnK"><span id="gbqfsa">CALENDAR</span></button> <button class="gbqfba" aria-label="Google Search" id="gbqfba" name="btnK"><span id="gbqfsa">PROJECT INFO</span></button> <span id=":29" class="aw5"></span></div>';
    template1 = "<div>Search with Bing</div>";
    app.directive("myDirective", function() {
      return {
        restrict: 'EA',
        replace: true,
        template: project_tabs
      };
    });
    return angular.bootstrap(html, ['Binged'], []);
  });

}).call(this);
